language: c
compiler: gcc
before_script: autoreconf -if
sudo: false
dist: trusty
script: /bin/true

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EtIbgFu1PVycfPsKC+bEl1cJYlsH3iIDbZU8JRcVcUAWn/NXAnb04uwKOC2a7MjJv6arxoLoiuPYNO+yV5zeZIy6oOfO4TFR8OM/qdWXaV1EwWnQiDtQweRpte2uvd52UiDMFPch2HvNzRCoh+NMjU5/S89F8N3oN7dnPX/DGYnvEcet4WPkh8WND+Y+4DoElbENyl+/5MPF8dCNlTFuZJ/UDKCWJSpfo79DjO/CLek6XmoQwnZ9I1KE4zWdp/7+0ZbHFS8iJ4NRw4LrBIQozuaHGVtrpVfloJ+wjLFNh2FdMMfg+S7A825FlkXhT/YQCDy6+VUsPfmtlHaHXSOGQW/rHysnkF0490nIRIefO2BrGpNmM0SmgWviQ7qFFSsZo8mDZ/O9rRbR/3XipzklwhmE9L3iVr6w/Chr9H16IR92mrISATME2sATQIvNoSuwRyZnv8etNjSV1hCSKiqjdFCBzYe7DO1R265iaxRb4C6Oe7Gef3v8qWFtY5kckAhQzuzSr4LtrW3anm53NUUdhScfEeSIQ8sWNmT1N5eMsGtVBamgpPFsp/+yXw4YHcJEwjE6xX+bauPXtzdaomXX4KVLC9tNciAxxY33N+1XX1S7yfzHJ4u8cu93DXdhRTaC6kiWKeyH2Kena/MlvbsIyFX3tNBYf3uChO8//zIMtHA="

addons:
  apt:
    packages:
    - autopoint
    - cifs-utils
    - debhelper
    - dh-apparmor
    - dh-autoreconf
    - dh-python
    - dh-systemd
    - dnsutils
    - docbook-xml
    - docbook-xsl
    - dpkg-dev
    - krb5-config
    - libaugeas-dev
    - libc-ares-dev
    - libcollection-dev
    - libdbus-1-dev
    - libdhash-dev
    - libglib2.0-dev
    - libhttp-parser-dev
    - libini-config-dev
    - libjansson-dev
    - libkeyutils-dev
    - libkrb5-dev
    - libldap2-dev
    - libldb-dev
    - libltdl-dev
    - libnfsidmap-dev
    - libnl-3-dev
    - libnl-route-3-dev
    - libnspr4-dev
    - libnss3-dev
    - libpam0g-dev
    - libpcre3-dev
    - libpopt-dev
    - libsasl2-dev
    - libselinux1-dev
    - libsemanage1-dev
    - libsmbclient-dev
    - libtalloc-dev
    - libtdb-dev
    - libtevent-dev
    - libxml2-utils
    - lsb-release
    - python-dev
    - python-setuptools
    - python3-dev
    - python3-setuptools
    - quilt
    - samba-dev
    - systemd
    - xml-core
    - xsltproc
  coverity_scan:
    project:
      name: "sgallagher/sssd"
      description: "Build submitted via Travis CI"
    notification_email: sgallagh@redhat.com
    build_command_prepend: "autoreconf -if && ./configure --enable-krb5-locator-plugin 	--datadir=/usr/share/ 	--with-environment-file=/etc/default/sssd 	--with-ldb-lib-dir=/usr/lib64/ldb/modules/ldb 	--with-krb5-plugin-path=/usr/lib64/krb5/plugins/libkrb5 	--enable-nsslibdir=/lib64 	--enable-pammoddir=/lib64/security 	--disable-static 	--disable-rpath 	--with-autofs 	--with-ssh 	--with-initscript=systemd --with-systemdunitdir=/lib/systemd/system 	--with-sudo && make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

